// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://ljxwljvodiwtmkiseukb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqeHdsanZvZGl3dG1raXNldWtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MDk3NjAsImV4cCI6MjA2MTI4NTc2MH0.XpOdfBHw2ai78Rg1fbyxs1F4Y1HjDitnu0jNFQQVQb8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);